[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-arena"
version = "0.1.0"
description = "A tool for benchmarking multiple machine learning models on tabular datasets"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]